name: Continous delivery

on:
  workflow_dispatch:

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get Docker version
        working-directory: ./hangman-api
        run: docker build -t jperari766a/hangman-api-cep-grupo-b:latest
